eureka:
  client:
    fetchRegistry: true  # Fetch registry from Eureka server
    registerWithEureka: true  # Register this service with Eureka
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ivxstudio  # Database URL
    username: ivxapp # Username
    password: ivx@studio # Password
    hikari:
      poolName: HikariCP  # Connection pool name (HikariCP is the default)
      minimumIdle: 2  # Minimum number of idle connections
      maximumPoolSize: 10  # Maximum number of connections in the pool
      idleTimeout: 600000  # Idle timeout in milliseconds (10 minutes)
      maxLifetime: 1800000  # Max lifetime of a connection in milliseconds (30 minutes)
      connectionTimeout: 30000  # Connection timeout in milliseconds (5 minutes)
  jpa:
    show-sql: true  # Enable showing of SQL statements in logs
    hibernate:
      ddl-auto: update  # Schema update behavior (create, create-drop, update, validate)

IVX-SERVER: http://localhost:8761
IVX-PRODUCT-SERVICE: http://localhost:8001
IVX-USER-SERVICE: http://localhost:8002
IVX-REVIEW-SERVICE: http://localhost:8003
IVX-AUTH-SERVICE: http://localhost:8004
