eureka:
  client:
    fetchRegistry: true  # Fetch registry from Eureka server
    registerWithEureka: true  # Register this service with Eureka
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL
